name: full
version: 0.0.1
description: A sample command-line application that installs and runs mailhog
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  args: ^2.3.1
  dcli: ^1.33.0
  http: ^0.13.4
  lint_hard: ^3.0.0-beta.1
  settings_yaml: ^3.4.2


executable:
  dmailhog: 