name: full
version: 0.0.1
publish_to: https://beta.onepub.dev/api/jbbxpsdavu/
description: A sample command-line application that installs and runs mailhog
environment: 
  sdk: '>=3.0.0 <4.0.0'
  flutter: 
dependencies: 
  args: ^2.3.1
  dcli: 3.2.7
  dcli_core: 3.2.7
  http: ^0.13.4
  path: ^1.8.1
  settings_yaml: ^7.0.0
dev_dependencies: 
  lint_hard: ^4.0.0
executables: 
  full: 
    full: 
