name: dcli
version: 1.35.3
homepage: https://dcli.onepub.dev
documentation: https://dcli.onepub.dev
description: Dart console SDK - write console (cli) apps/scripts using dart.
repository: https://github.com/onepub-dev/dcli
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  archive: ^3.0.0
  args: ^2.0.0
  async: ^2.5.0
  chunked_stream: ^1.4.1
  collection: ^1.15.0
  convert: ^3.0.1
  crypto: ^3.0.0
  csv: ^5.0.1
  dart_console2: ^2.0.0
  dcli_core: ^1.35.3
  equatable: ^2.0.0
  ffi: ^2.0.0
  file: ^6.1.0
  glob: ^2.0.0
  ini: ^2.1.0
  logging: ^1.0.2
  meta: ^1.3.0
  mime: ^1.0.1
  path: ^1.8.0
  posix: ^4.1.0
  pub_semver: ^2.0.0
  pubspec2: ^2.4.1
  scope: ^3.0.0
  settings_yaml: ^3.4.2
  stacktrace_impl: ^2.3.0
  system_info2: ^2.0.3
  uuid: ^3.0.0
  validators2: ^3.0.0
  win32: ^2.7.0
  yaml: ^3.0.0
dev_dependencies: 
  hex: ^0.2.0
  lint_hard: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.0.0
dependency_overrides: 
  dcli_core: 
    path: ../dcli_core
executables: 
  dcli: 
  dcli_complete: 
  dcli_install: 
platforms: 
  linux: 
  macos: 
  windows: 
