name: console_simple
version: 0.0.1
description: A simple command-line application created by dcli
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter:
dependencies:
  dcli: 3.3.4
  dcli_core: 3.3.4
dev_dependencies:
  lint_hard: ^3.0.0
